import { CombinedState } from "@reduxjs/toolkit";
import { AppState } from "./app/slice";
import Head from "next/head";

export type StoreState = CombinedState<{
  app: AppState;
}>;

export const selectRootState = (state: StoreState) => state;

// <title>Sharper Image Code Exam</title>
// <meta content="width=device-width, initial-scale=1" name="viewport" />
// <meta name="description" content="Generated by create next app" />
// <link rel="icon" href="/favicon.ico" />
